#service config
spring:
  application:
    name: service-patient
  config:
    import: "configserver:"
  profiles:
    activete: test
#server
server:
  port: 8003
#eureka config
eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka