# Configuração do banco de dados
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
      path: /h2-console
      web-allowed: true
