#Server config
server:
  port: 8888
#Spring config
spring:
  application:
    name: config-server
  profiles:
    active:
      - native
#Eureka config
eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka